### ISSUE TITLE
Release of version 1.1

### ISSUE THREAD

**Issue by adhxtry** [sneaky0potato/litesoph_iiserb#8]
### Clone workflow

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

Clone workflow option earlier would return an error, which has been fixed.

### Missing __init__.py Files

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

A few folders which contained essential functions for post processing were missing `__init__.py` files

These files are necessary for python to build the directories as a module, hence was causing issues with the post processing

Such file was added in missing places.

### Windows Portability (Postponed to 1.2)

> ❌ Fixed?
> ❌ Review#1
> ❌ Review#2

Litesoph can now be installed and used on windows using wsl for submitting commands locally.

### Average spectrum (Octopus)

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

Average Spectrum utility would return an error about a missing argument `self.restart`

We added a line that `self.restart=False` in the update parameter function

Reason: The two options are to either pass the parameter as True/False or to remove it completely,

The said parameter was being inherited to from a class above we set it to False because no restart information is needed in the plot post processing

### Kohn-Sham Decomposition (Octopus)

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

Kohn-sham Decomposition is a prebuilt function in GPAW and works perfectly fine in the same engine.

For octopus, there was an issue with Tkinter , Tkinter was looking for a string input while the code was passing "empty" causing an error

We added a line to pass an empty string in the input

The code was well written but was causing an error when the passed inputs were 1 and 1.

For such input, a test condition was added to pad the generated matrix for contour plot.

The condition picks the maximum of the input and 2 and then generates necessary padding for 

### MO tracking octopus

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

### Proceed button grey-out when job is running

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

### Box Dimensions (Octopus)

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

Box Dimensions input was not being captured from gui, when shape is parallelopiped.

### Queue remote submit

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

Hold user to same job until the job is completed on the remote

### [FIX] Task mode

> - [x] Fixed?
> - [x] Review#1
> - [x] Review#2

### Documentation

> - [x] Fixed?
> - [ ] Review#1
> - [ ] Review#2

**Comment by svaradh** [comment]
1. Cloning should bring flowchart pointer to beginning of compound blocks to be executed in new workflow.
2. Windows portability to ensure through back-end options, preferably through wsl.
3. Redundant variables (like self.restart) should not be "inherited" by methods that do not require the context.
4. Tkinter issue with Output=None should be implemented through an if condition.
5.

**Comment by sneaky0potato** [comment]
Gpaw point_group condition to be explored later (And why was it True as Default)
